refactor: tag p x tag h3
diegocoliveira/equipe10-dev-html pull request #12
Opened 2022-05-11 20:21 UTC by janascher

Foi alterado a tag <p> pela tag <h3>.

2022-05-11 21:02 UTC, diegocoliveira submitted a review, later dismissed

2022-05-11 21:16 UTC, Fabio-Cesar requested changes
Shouldn't it be h2? The html file only has a &lt;h1&gt; tag defined before.

2022-05-11 21:54 UTC, janascher commented
Alterado a tag h3 para h2 @Fabio-Cesar

2022-05-12 02:43 UTC, Fabio-Cesar approved these changes

2022-05-13 02:11 UTC, closed without merging