chore: add files
diegocoliveira/equipe10-dev-html pull request #2
Opened 2022-05-03 21:48 UTC by janascher

Favor aprovar

2022-05-03 21:50 UTC, diegocoliveira commented
Será um css para cada página ou será um arquivos css por projeto?

2022-05-03 22:05 UTC, janascher commented
É uma boa prática ter apenas um arquivo CSS.

2022-05-03 22:08 UTC, diegocoliveira requested changes
Sugiro que altere o nome do arquivo css.

2022-05-03 22:26 UTC, janascher commented
Alterado o nome do arquivo command.css para style.css.

2022-05-03 22:31 UTC, diegocoliveira approved these changes
OK

2022-05-03 22:48 UTC, Fabio-Cesar requested changes
Deixe um breve comentário do que a sua pull request adiciona ao conteúdo da main nessa caixa de mensagens. Fora isso, o conteúdo está OK!

2022-05-03 22:58 UTC, janascher commented
@Fabio-Cesar decidi editar a primeira mensagem, a de quando abri a PR, ficando deste modo:

"Adicionado os primeiros arquivos do guia de comandos simplificado de Git e GitHub.
Favor aprovar."

2022-05-03 23:04 UTC, Fabio-Cesar approved these changes

2022-05-04 01:29 UTC, isadoramg approved these changes

2022-05-04 22:21 UTC, closed without merging

2022-05-04 22:21 UTC, janascher commented
PR fechada.