chore:add-perfil-page-equipe
diegocoliveira/equipe10-dev-html pull request #20
Opened 2022-05-12 18:33 UTC by diegocoliveira

Adicionei o meu perfil e alterei o layout dos outros colaboradores

2022-05-12 18:35 UTC, Fabio-Cesar approved these changes, later dismissed

2022-05-12 18:42 UTC, janascher requested changes
Percebi que a tag img falta ser fechada.

2022-05-12 19:02 UTC, diegocoliveira commented
correções feitas

2022-05-13 01:00 UTC, janascher approved these changes

2022-05-13 01:01 UTC, Fabio-Cesar approved these changes

2022-05-13 01:01 UTC, isadoramg approved these changes

2022-05-13 01:01 UTC, merged