pagina equipe criada
diegocoliveira/equipe10-dev-html pull request #6
Opened 2022-05-05 16:00 UTC by isadoramg

2022-05-05 18:09 UTC, diegocoliveira requested changes
Eu não entendi o uso da tag <div> se puder fazer uma verificação e enviar novamente

2022-05-05 19:25 UTC, Fabio-Cesar requested changes
É necessário corrigir o uso das tags de fechamento para algumas tags de abertura, e também corrigir a semântica no uso da tag &lt;fieldset&gt;.

2022-05-06 03:01 UTC, Fabio-Cesar approved these changes

2022-05-06 03:01 UTC, diegocoliveira approved these changes

2022-05-08 21:29 UTC, janascher approved these changes

2022-05-10 17:58 UTC, merged